# Generated by Django 4.2.1 on 2023-05-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='ID работника')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Профиль работника',
                'verbose_name_plural': 'Профили работников',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes', verbose_name='QR-код пользователя')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='Текущий процент скидки')),
                ('previous_discount_percentage', models.IntegerField(default=0, verbose_name='Предыдущий процент скидки')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма потраченных средств')),
                ('is_special', models.BooleanField(default=False, verbose_name='VIP клиент')),
                ('menu_total', models.FloatField(default=0.0, verbose_name='Сумма текущего меню')),
                ('previous_menu_total', models.FloatField(default=0.0, verbose_name='Предыдущая сумма меню')),
                ('menu_total_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Время внесения суммы меню')),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
            },
        ),
    ]
