# Generated by Django 4.2.1 on 2023-06-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='digital_signature',
            field=models.TextField(default=0, verbose_name='Цифровая подпись'),
        ),
    ]
