# Generated by Django 4.2.1 on 2023-06-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_application', '0002_userprofile_digital_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='digital_signature',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(default=0, max_length=256, verbose_name='Цифровая подпись'),
        ),
    ]
