# Generated by Django 4.2.1 on 2023-06-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_application', '0004_alter_userprofile_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobprofile',
            old_name='phone_number',
            new_name='job_phone_number',
        ),
    ]
